# Canny parameters
blur_kernel: 5
sigma: 1
threshold1: 50
threshold2: 118

ASPECT_SLOT_MIN: 1
ASPECT_SLOT_MAX: 10
AREA_SLOT_MIN_R: 500 # [pixel]   
AREA_SLOT_MAX_R: 45000 # [pixel] 

AREA_MIN_M: 50000 # [pixels] 
AREA_MAX_M: 5000000 # [pixel] 

TOL_RADIUS: 10 # [pixels] to filter duplicated detected boxes

RS_x:  0.4766 # camera spatial resolution [mm/px] along x
RS_y:  0.4770 # camera spatial resolution [mm/px] along y

W: 2048  # sensor width [pixel]
H:  1088  # sensor heigth [pixel]

m_th_rel : 0.12  # minimum threshold on moments relative difference (m00, m10, m01, m20, m11, m02, m30, m21, m12, m03)

INTENSITY_HOLE_MAX_R: 108 # threshold on feature brightness to filter features different from holes in Symmetry_Via_Rectangle.py
INTENSITY_HOLE_MAX_M: 54 # threshold on feature brightness to filter features different from holes in Symmetry_Via_Moments.py

position_mm: 5.0 # uncertainty on difference between features position
length_mm: 3.0 # uncertainty on features lengths
theta_degree: 6.0 # uncertainty on features orientation